# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scion_grpc/hopfields.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='scion_grpc/hopfields.proto',
  package='proto.control_plane.v1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1ascion_grpc/hopfields.proto\x12\x16proto.control_plane.v1\"\xb5\x01\n\x1cHopFieldsRegistrationRequest\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x12\n\nsegment_id\x18\x02 \x01(\r\x12\x33\n\thop_field\x18\x03 \x01(\x0b\x32 .proto.control_plane.v1.HopField\x12\x39\n\x0fpeer_hop_fields\x18\x04 \x03(\x0b\x32 .proto.control_plane.v1.HopField\"J\n\x08HopField\x12\x0f\n\x07ingress\x18\x01 \x01(\x04\x12\x0e\n\x06\x65gress\x18\x02 \x01(\x04\x12\x10\n\x08\x65xp_time\x18\x03 \x01(\r\x12\x0b\n\x03mac\x18\x04 \x01(\x0c\"\x1f\n\x1dHopFieldsRegistrationResponse\"\x1f\n\x1dRemoveExpiredHopFieldsRequest\" \n\x1eRemoveExpiredHopFieldsResponse2\xb3\x02\n\x1cHopFieldsRegistrationService\x12\x86\x01\n\x15HopFieldsRegistration\x12\x34.proto.control_plane.v1.HopFieldsRegistrationRequest\x1a\x35.proto.control_plane.v1.HopFieldsRegistrationResponse\"\x00\x12\x89\x01\n\x16RemoveExpiredHopFields\x12\x35.proto.control_plane.v1.RemoveExpiredHopFieldsRequest\x1a\x36.proto.control_plane.v1.RemoveExpiredHopFieldsResponse\"\x00\x62\x06proto3'
)




_HOPFIELDSREGISTRATIONREQUEST = _descriptor.Descriptor(
  name='HopFieldsRegistrationRequest',
  full_name='proto.control_plane.v1.HopFieldsRegistrationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='proto.control_plane.v1.HopFieldsRegistrationRequest.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='segment_id', full_name='proto.control_plane.v1.HopFieldsRegistrationRequest.segment_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hop_field', full_name='proto.control_plane.v1.HopFieldsRegistrationRequest.hop_field', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='peer_hop_fields', full_name='proto.control_plane.v1.HopFieldsRegistrationRequest.peer_hop_fields', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=236,
)


_HOPFIELD = _descriptor.Descriptor(
  name='HopField',
  full_name='proto.control_plane.v1.HopField',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ingress', full_name='proto.control_plane.v1.HopField.ingress', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='egress', full_name='proto.control_plane.v1.HopField.egress', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='exp_time', full_name='proto.control_plane.v1.HopField.exp_time', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mac', full_name='proto.control_plane.v1.HopField.mac', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=312,
)


_HOPFIELDSREGISTRATIONRESPONSE = _descriptor.Descriptor(
  name='HopFieldsRegistrationResponse',
  full_name='proto.control_plane.v1.HopFieldsRegistrationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=314,
  serialized_end=345,
)


_REMOVEEXPIREDHOPFIELDSREQUEST = _descriptor.Descriptor(
  name='RemoveExpiredHopFieldsRequest',
  full_name='proto.control_plane.v1.RemoveExpiredHopFieldsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=347,
  serialized_end=378,
)


_REMOVEEXPIREDHOPFIELDSRESPONSE = _descriptor.Descriptor(
  name='RemoveExpiredHopFieldsResponse',
  full_name='proto.control_plane.v1.RemoveExpiredHopFieldsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=380,
  serialized_end=412,
)

_HOPFIELDSREGISTRATIONREQUEST.fields_by_name['hop_field'].message_type = _HOPFIELD
_HOPFIELDSREGISTRATIONREQUEST.fields_by_name['peer_hop_fields'].message_type = _HOPFIELD
DESCRIPTOR.message_types_by_name['HopFieldsRegistrationRequest'] = _HOPFIELDSREGISTRATIONREQUEST
DESCRIPTOR.message_types_by_name['HopField'] = _HOPFIELD
DESCRIPTOR.message_types_by_name['HopFieldsRegistrationResponse'] = _HOPFIELDSREGISTRATIONRESPONSE
DESCRIPTOR.message_types_by_name['RemoveExpiredHopFieldsRequest'] = _REMOVEEXPIREDHOPFIELDSREQUEST
DESCRIPTOR.message_types_by_name['RemoveExpiredHopFieldsResponse'] = _REMOVEEXPIREDHOPFIELDSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HopFieldsRegistrationRequest = _reflection.GeneratedProtocolMessageType('HopFieldsRegistrationRequest', (_message.Message,), {
  'DESCRIPTOR' : _HOPFIELDSREGISTRATIONREQUEST,
  '__module__' : 'scion_grpc.hopfields_pb2'
  # @@protoc_insertion_point(class_scope:proto.control_plane.v1.HopFieldsRegistrationRequest)
  })
_sym_db.RegisterMessage(HopFieldsRegistrationRequest)

HopField = _reflection.GeneratedProtocolMessageType('HopField', (_message.Message,), {
  'DESCRIPTOR' : _HOPFIELD,
  '__module__' : 'scion_grpc.hopfields_pb2'
  # @@protoc_insertion_point(class_scope:proto.control_plane.v1.HopField)
  })
_sym_db.RegisterMessage(HopField)

HopFieldsRegistrationResponse = _reflection.GeneratedProtocolMessageType('HopFieldsRegistrationResponse', (_message.Message,), {
  'DESCRIPTOR' : _HOPFIELDSREGISTRATIONRESPONSE,
  '__module__' : 'scion_grpc.hopfields_pb2'
  # @@protoc_insertion_point(class_scope:proto.control_plane.v1.HopFieldsRegistrationResponse)
  })
_sym_db.RegisterMessage(HopFieldsRegistrationResponse)

RemoveExpiredHopFieldsRequest = _reflection.GeneratedProtocolMessageType('RemoveExpiredHopFieldsRequest', (_message.Message,), {
  'DESCRIPTOR' : _REMOVEEXPIREDHOPFIELDSREQUEST,
  '__module__' : 'scion_grpc.hopfields_pb2'
  # @@protoc_insertion_point(class_scope:proto.control_plane.v1.RemoveExpiredHopFieldsRequest)
  })
_sym_db.RegisterMessage(RemoveExpiredHopFieldsRequest)

RemoveExpiredHopFieldsResponse = _reflection.GeneratedProtocolMessageType('RemoveExpiredHopFieldsResponse', (_message.Message,), {
  'DESCRIPTOR' : _REMOVEEXPIREDHOPFIELDSRESPONSE,
  '__module__' : 'scion_grpc.hopfields_pb2'
  # @@protoc_insertion_point(class_scope:proto.control_plane.v1.RemoveExpiredHopFieldsResponse)
  })
_sym_db.RegisterMessage(RemoveExpiredHopFieldsResponse)



_HOPFIELDSREGISTRATIONSERVICE = _descriptor.ServiceDescriptor(
  name='HopFieldsRegistrationService',
  full_name='proto.control_plane.v1.HopFieldsRegistrationService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=415,
  serialized_end=722,
  methods=[
  _descriptor.MethodDescriptor(
    name='HopFieldsRegistration',
    full_name='proto.control_plane.v1.HopFieldsRegistrationService.HopFieldsRegistration',
    index=0,
    containing_service=None,
    input_type=_HOPFIELDSREGISTRATIONREQUEST,
    output_type=_HOPFIELDSREGISTRATIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RemoveExpiredHopFields',
    full_name='proto.control_plane.v1.HopFieldsRegistrationService.RemoveExpiredHopFields',
    index=1,
    containing_service=None,
    input_type=_REMOVEEXPIREDHOPFIELDSREQUEST,
    output_type=_REMOVEEXPIREDHOPFIELDSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_HOPFIELDSREGISTRATIONSERVICE)

DESCRIPTOR.services_by_name['HopFieldsRegistrationService'] = _HOPFIELDSREGISTRATIONSERVICE

# @@protoc_insertion_point(module_scope)
