# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from scion_grpc import hopfields_pb2 as scion__grpc_dot_hopfields__pb2


class HopFieldsRegistrationServiceStub(object):
    """import "proto/control_plane/v1/seg.proto";

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HopFieldsRegistration = channel.unary_unary(
                '/proto.control_plane.v1.HopFieldsRegistrationService/HopFieldsRegistration',
                request_serializer=scion__grpc_dot_hopfields__pb2.HopFieldsRegistrationRequest.SerializeToString,
                response_deserializer=scion__grpc_dot_hopfields__pb2.HopFieldsRegistrationResponse.FromString,
                )
        self.RemoveExpiredHopFields = channel.unary_unary(
                '/proto.control_plane.v1.HopFieldsRegistrationService/RemoveExpiredHopFields',
                request_serializer=scion__grpc_dot_hopfields__pb2.RemoveExpiredHopFieldsRequest.SerializeToString,
                response_deserializer=scion__grpc_dot_hopfields__pb2.RemoveExpiredHopFieldsResponse.FromString,
                )


class HopFieldsRegistrationServiceServicer(object):
    """import "proto/control_plane/v1/seg.proto";

    """

    def HopFieldsRegistration(self, request, context):
        """HopFieldsRegistration registers hop fields at the remote service
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveExpiredHopFields(self, request, context):
        """Remove expired hop fields at the remote service
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HopFieldsRegistrationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HopFieldsRegistration': grpc.unary_unary_rpc_method_handler(
                    servicer.HopFieldsRegistration,
                    request_deserializer=scion__grpc_dot_hopfields__pb2.HopFieldsRegistrationRequest.FromString,
                    response_serializer=scion__grpc_dot_hopfields__pb2.HopFieldsRegistrationResponse.SerializeToString,
            ),
            'RemoveExpiredHopFields': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveExpiredHopFields,
                    request_deserializer=scion__grpc_dot_hopfields__pb2.RemoveExpiredHopFieldsRequest.FromString,
                    response_serializer=scion__grpc_dot_hopfields__pb2.RemoveExpiredHopFieldsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.control_plane.v1.HopFieldsRegistrationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HopFieldsRegistrationService(object):
    """import "proto/control_plane/v1/seg.proto";

    """

    @staticmethod
    def HopFieldsRegistration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.control_plane.v1.HopFieldsRegistrationService/HopFieldsRegistration',
            scion__grpc_dot_hopfields__pb2.HopFieldsRegistrationRequest.SerializeToString,
            scion__grpc_dot_hopfields__pb2.HopFieldsRegistrationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveExpiredHopFields(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.control_plane.v1.HopFieldsRegistrationService/RemoveExpiredHopFields',
            scion__grpc_dot_hopfields__pb2.RemoveExpiredHopFieldsRequest.SerializeToString,
            scion__grpc_dot_hopfields__pb2.RemoveExpiredHopFieldsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
